- name: Make sure chrony service is installed
  package:
    name: "{{ ntp_pkg }}"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 3

- name: Make sure chrony service is running
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes
