- name: Make sure chrony service is installed
  package:
    name: "{{ ntp_package }}"
    state: present
  register: _pkg
  until: _pkg is succeeded
  retries: 3

- name: Update permissions on chrony pid folder on EL 8
  file:
    path: /run/chrony/
    owner: root
    group: root
    state: directory
  when:
    - ansible_facts.os_family == "RedHat"
    - ansible_facts.distribution_major_version|int >= 8

- name: Make sure chrony service is running
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes
