- name: Make sure glibc library is the latest
  package:
    name: "{{ glibc_pkg }}"
    state: latest
  register: _pkg
  until: _pkg is succeeded
  retries: 3

- name: Make sure numactl is installed
  package:
    name: "{{ numactl_pkg }}"
    state: latest
  register: _pkg
  until: _pkg is succeeded
  retries: 3
