- name: Make sure glibc library is the latest
  package:
    name: "{{ gnu_c_lib }}"
    state: latest
  register: _pkg
  until: _pkg is succeeded
  retries: 3

- name: Make sure numactl is installed
  package:
    name: "{{ numactl }}"
    state: latest
  register: _pkg
  until: _pkg is succeeded
  retries: 3
