- name: Create new SystemD service to disable THP
  copy:
    src: thp.service
    dest: /etc/systemd/system/thp.service
    owner: root
    group: root
  register: thp

- name: Reload systemd
  systemd:
    daemon_reexec: yes
  when: thp is changed

- name: Enable and start thp.service
  service:
    name: thp
    state: started
    enabled: yes
